Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from graspologic.simulations import sbm
import numpy as np
from graphbook_code import dcsbm, generate_dcsbm_pmtx, \
                           generate_sbm_pmtx

n = 150  # the number of nodes
# human brains have homophilic block structure
Bhum = np.array([[0.2, 0.02], [0.02, 0.2]])
# alien brains add degree-correction
theta_alien = np.tile(np.linspace(1.5, 0.5, n // 2), 2)

# generate human and alien brain network
np.random.seed(0)
A_human, z = sbm([n // 2, n // 2], Bhum, return_labels=True)
A_alien = dcsbm(z, theta_alien, Bhum)

Phum = generate_sbm_pmtx(z, Bhum)
Palien = generate_dcsbm_pmtx(z, theta_alien, Bhum)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 15[0m
[1;32m     13[0m np[38;5;241m.[39mrandom[38;5;241m.[39mseed([38;5;241m0[39m)
[1;32m     14[0m A_human, z [38;5;241m=[39m sbm([n [38;5;241m/[39m[38;5;241m/[39m [38;5;241m2[39m, n [38;5;241m/[39m[38;5;241m/[39m [38;5;241m2[39m], Bhum, return_labels[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[0;32m---> 15[0m A_alien [38;5;241m=[39m [43mdcsbm[49m[43m([49m[43mz[49m[43m,[49m[43m [49m[43mtheta_alien[49m[43m,[49m[43m [49m[43mBhum[49m[43m)[49m
[1;32m     17[0m Phum [38;5;241m=[39m generate_sbm_pmtx(z, Bhum)
[1;32m     18[0m Palien [38;5;241m=[39m generate_dcsbm_pmtx(z, theta_alien, Bhum)

File [0;32m/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/graphbook_code/sbm.py:54[0m, in [0;36mdcsbm[0;34m(z, theta, B, directed, loops, return_prob)[0m
[1;32m     50[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m     51[0m [38;5;124;03mA function to sample a DCSBM.[39;00m
[1;32m     52[0m [38;5;124;03m"""[39;00m
[1;32m     53[0m P [38;5;241m=[39m generate_dcsbm_pmtx(z, theta, B)
[0;32m---> 54[0m robj [38;5;241m=[39m [43msample_edges[49m(P, directed[38;5;241m=[39mdirected, loops[38;5;241m=[39mloops)
[1;32m     55[0m [38;5;28;01mif[39;00m return_prob:
[1;32m     56[0m     robj [38;5;241m=[39m (robj, P)

[0;31mNameError[0m: name 'sample_edges' is not defined

