Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from graphbook_code import dcsbm

nk = 100  # 100 nodes per community
zs = np.repeat([1, 2], nk)
B = np.array([[0.6, 0.3], [0.3, 0.6]])
theta = b = np.repeat([1, .2, 1, .2], nk // 2)
deg_map = {1: "Core", 0.2: "Per."}

zs_deg = [f"{deg_map[theta[i]]:s}" for i in range(len(theta))]
zs_aug = [f"{z:d}, {deg:s}" for z, deg in zip(zs, zs_deg)]

A, P = dcsbm(zs, theta, B, return_prob=True)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[13], line 12[0m
[1;32m      9[0m zs_deg [38;5;241m=[39m [[38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mdeg_map[theta[i]][38;5;132;01m:[39;00m[38;5;124ms[39m[38;5;132;01m}[39;00m[38;5;124m"[39m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;28mlen[39m(theta))]
[1;32m     10[0m zs_aug [38;5;241m=[39m [[38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mz[38;5;132;01m:[39;00m[38;5;124md[39m[38;5;132;01m}[39;00m[38;5;124m, [39m[38;5;132;01m{[39;00mdeg[38;5;132;01m:[39;00m[38;5;124ms[39m[38;5;132;01m}[39;00m[38;5;124m"[39m [38;5;28;01mfor[39;00m z, deg [38;5;129;01min[39;00m [38;5;28mzip[39m(zs, zs_deg)]
[0;32m---> 12[0m A, P [38;5;241m=[39m [43mdcsbm[49m[43m([49m[43mzs[49m[43m,[49m[43m [49m[43mtheta[49m[43m,[49m[43m [49m[43mB[49m[43m,[49m[43m [49m[43mreturn_prob[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/graphbook_code/sbm.py:54[0m, in [0;36mdcsbm[0;34m(z, theta, B, directed, loops, return_prob)[0m
[1;32m     50[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m     51[0m [38;5;124;03mA function to sample a DCSBM.[39;00m
[1;32m     52[0m [38;5;124;03m"""[39;00m
[1;32m     53[0m P [38;5;241m=[39m generate_dcsbm_pmtx(z, theta, B)
[0;32m---> 54[0m robj [38;5;241m=[39m [43msample_edges[49m(P, directed[38;5;241m=[39mdirected, loops[38;5;241m=[39mloops)
[1;32m     55[0m [38;5;28;01mif[39;00m return_prob:
[1;32m     56[0m     robj [38;5;241m=[39m (robj, P)

[0;31mNameError[0m: name 'sample_edges' is not defined

